# Generated by Django 4.2.2 on 2023-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_entry_options_alter_genre_options_entry_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='entries', to='lists.genre', verbose_name='жанры'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='medium_type',
            field=models.CharField(choices=[('Аниме', 'Аниме'), ('Сериал', 'Сериал'), ('Фильм', 'Фильм'), ('Книга', 'Книга'), ('Другое', 'Другое')], default='Аниме', max_length=10, verbose_name='вид медиа'),
        ),
    ]
